-- Regression test for gh-2483
env = require('test_run')
---
...
test_run = env.new()
---
...
engine = test_run:get_cfg('engine')
---
...
box.sql.execute('pragma sql_default_engine=\''..engine..'\'')
---
- rowcount: 0
...
box.schema.user.grant('guest', 'read,write,execute', 'universe')
---
...
-- Create a table and insert a datum
box.sql.execute([[CREATE TABLE t(id int PRIMARY KEY)]])
---
- rowcount: 1
...
box.sql.execute([[INSERT INTO t (id) VALUES (1)]])
---
- rowcount: 1
...
-- Sanity check
box.sql.execute([[SELECT * FROM t]])
---
- metadata:
  - name: ID
    type: INTEGER
  rows:
  - [1]
...
test_run:cmd('restart server default');
-- Connect to ourself
c = require('net.box').connect(os.getenv("LISTEN"))
---
...
-- This segfaults due to gh-2483 since
-- before the patch sql schema was read on-demand.
-- Which could obviously lead to access denied error.
c:eval([[ return box.sql.execute('SELECT * FROM t') ]])
---
- {'metadata': [{'name': 'ID', 'type': 'INTEGER'}], 'rows': [[1]]}
...
-- sql.execute([[SELECT * FROM t]])
box.sql.execute([[DROP TABLE t]])
---
- rowcount: 1
...
box.schema.user.revoke('guest', 'read,write,execute', 'universe')
---
...
